// src/components/ThemeSwitcher.svelte
<script lang="ts">
  import Sun from "@lucide/svelte/icons/sun";
  import Moon from "@lucide/svelte/icons/moon";
  import Monitor from "@lucide/svelte/icons/monitor";
  import { Button } from "$lib/components/ui/button";
  import { cn } from "$lib/utils";
  import type { UITheme } from "$lib/types/ui";

  interface Props {
    value: UITheme;
    onChange: (theme: UITheme) => void;
  }

  let { value, onChange }: Props = $props();

  const options: Array<{ id: UITheme; Icon: typeof Sun; label: string }> = [
    { id: "light", Icon: Sun, label: "Light" },
    { id: "dark", Icon: Moon, label: "Dark" },
    { id: "system", Icon: Monitor, label: "System" },
  ];
</script>

<div class="inline-flex items-center gap-1 rounded-lg border border-border bg-card/60 p-1 backdrop-blur">
  {#each options as option}
    {@const Icon = option.Icon}
    <Button
      type="button"
      variant="ghost"
      size="sm"
      aria-pressed={option.id === value}
      onclick={() => onChange(option.id)}
      class={cn(
        "h-8 w-8 px-0 text-muted-foreground relative overflow-hidden transition-all duration-300",
        option.id === value && "bg-primary/10 text-primary"
      )}
      aria-label="Switch to {option.label} theme"
    >
      <span
        class={cn(
          "relative z-10 transition-opacity duration-300",
          option.id === value ? "opacity-100" : "opacity-60"
        )}
      >
        <Icon class="h-4 w-4" aria-hidden="true" />
      </span>
      <span class="sr-only">{option.label}</span>
    </Button>
  {/each}
</div>

// src/components/ThemeSwitcher.tsx
import { Monitor, Moon, Sun } from "lucide-react";
import type { ReactNode } from "react";
import { useEffect, useState } from "react";

import { cn } from "../lib/utils";
import { Button } from "./ui/button";
import type { UITheme } from "../types/ui";
import { anim } from "../lib/animations";

interface ThemeSwitcherProps {
  value: UITheme;
  onChange: (theme: UITheme) => void;
}

const options: Array<{ id: UITheme; icon: ReactNode; label: string }> = [
  { id: "light", icon: <Sun className="h-4 w-4" />, label: "Light" },
  { id: "dark", icon: <Moon className="h-4 w-4" />, label: "Dark" },
  { id: "system", icon: <Monitor className="h-4 w-4" />, label: "System" },
];

export function ThemeSwitcher({ value, onChange }: ThemeSwitcherProps) {
  const [previousValue, setPreviousValue] = useState<UITheme>(value);
  const [isTransitioning, setIsTransitioning] = useState(false);

  useEffect(() => {
    if (previousValue !== value) {
      setIsTransitioning(true);
      const timer = setTimeout(() => {
        setIsTransitioning(false);
        setPreviousValue(value);
      }, 300); // Match animation duration
      return () => clearTimeout(timer);
    }
  }, [value, previousValue]);

  return (
    <div className="inline-flex items-center gap-1 rounded-full border border-border bg-card/60 p-1 backdrop-blur">
      {options.map((option) => {
        const isActive = option.id === value;
        return (
          <Button
            key={option.id}
            type="button"
            variant="ghost"
            size="sm"
            aria-pressed={isActive}
            onClick={() => onChange(option.id)}
            className={cn(
              "h-8 w-8 px-0 text-muted-foreground relative overflow-hidden",
              anim("medium", "all"),
              isActive && "bg-primary/10 text-primary",
              isTransitioning && isActive && "animate-pulse",
            )}
          >
            <span
              className={cn(
                "relative z-10 transition-opacity duration-300",
                isActive ? "opacity-100" : "opacity-60"
              )}
            >
              {option.icon}
            </span>
            <span className="sr-only">{option.label}</span>
          </Button>
        );
      })}
    </div>
  );
}
